services:
  frontend:
    image: userwei/nycu_service-learning-nanao:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
  
  backend:
    image: userwei/nycu_service-learning-nanao:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://nanao_user:nanao_password@db:3306/nanao_db
      SESSION_SECRET: nanao_db
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nanao_db
      MYSQL_USER: nanao_user
      MYSQL_PASSWORD: nanao_password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
